
package pe.com.claro.eai.ws.ventas.plantillaws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import pe.com.claro.eai.ws.ventas.plantillaws.types.ConsultarRequest;
import pe.com.claro.eai.ws.ventas.plantillaws.types.ConsultarResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlantillaWSPortType", targetNamespace = "http://claro.com.pe/eai/ws/ventas/plantillaws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ pe.com.claro.eai.ws.baseschema.ObjectFactory.class,
		pe.com.claro.eai.ws.ventas.plantillaws.types.ObjectFactory.class })
public interface PlantillaWSPortType {

	/**
	 * 
	 * @param request
	 * @return returns
	 *         pe.com.claro.eai.ws.ventas.plantillaws.types.ConsultarResponse
	 */
	@WebMethod(action = "http://claro.com.pe/eai/ws/ventas/plantillaws/consultar")
	@WebResult(name = "consultarResponse", targetNamespace = "http://claro.com.pe/eai/ws/ventas/plantillaws/types", partName = "response")
	public ConsultarResponse consultar(
			@WebParam(name = "consultarRequest", targetNamespace = "http://claro.com.pe/eai/ws/ventas/plantillaws/types", partName = "request") ConsultarRequest request);

}
