
package pe.com.claro.eai.ws.ventas.plantillaws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlantillaWSService", targetNamespace = "http://claro.com.pe/eai/ws/ventas/plantillaws", wsdlLocation = "WEB-INF/wsdl/PlantillaWS.wsdl")
public class PlantillaWSService extends Service {

	private final static URL PLANTILLAWSSERVICE_WSDL_LOCATION;
	private final static WebServiceException PLANTILLAWSSERVICE_EXCEPTION;
	private final static QName PLANTILLAWSSERVICE_QNAME = new QName("http://claro.com.pe/eai/ws/ventas/plantillaws",
			"PlantillaWSService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = pe.com.claro.eai.ws.ventas.plantillaws.PlantillaWSService.class
					.getResource("/WEB-INF/wsdl/PlantillaWS.wsdl");
			if (url == null) {
				throw new MalformedURLException("/WEB-INF/wsdl/PlantillaWS.wsdl does not exist in the module.");
			}
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		PLANTILLAWSSERVICE_WSDL_LOCATION = url;
		PLANTILLAWSSERVICE_EXCEPTION = e;
	}

	public PlantillaWSService() {
		super(__getWsdlLocation(), PLANTILLAWSSERVICE_QNAME);
	}

	public PlantillaWSService(WebServiceFeature... features) {
		super(__getWsdlLocation(), PLANTILLAWSSERVICE_QNAME, features);
	}

	public PlantillaWSService(URL wsdlLocation) {
		super(wsdlLocation, PLANTILLAWSSERVICE_QNAME);
	}

	public PlantillaWSService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, PLANTILLAWSSERVICE_QNAME, features);
	}

	public PlantillaWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PlantillaWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns PlantillaWSPortType
	 */
	@WebEndpoint(name = "ebsPlantillaSB11")
	public PlantillaWSPortType getEbsPlantillaSB11() {
		return super.getPort(new QName("http://claro.com.pe/eai/ws/ventas/plantillaws", "ebsPlantillaSB11"),
				PlantillaWSPortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns PlantillaWSPortType
	 */
	@WebEndpoint(name = "ebsPlantillaSB11")
	public PlantillaWSPortType getEbsPlantillaSB11(WebServiceFeature... features) {
		return super.getPort(new QName("http://claro.com.pe/eai/ws/ventas/plantillaws", "ebsPlantillaSB11"),
				PlantillaWSPortType.class, features);
	}

	/**
	 * 
	 * @return returns PlantillaWSPortType
	 */
	@WebEndpoint(name = "ebsPlantillaSB12")
	public PlantillaWSPortType getEbsPlantillaSB12() {
		return super.getPort(new QName("http://claro.com.pe/eai/ws/ventas/plantillaws", "ebsPlantillaSB12"),
				PlantillaWSPortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns PlantillaWSPortType
	 */
	@WebEndpoint(name = "ebsPlantillaSB12")
	public PlantillaWSPortType getEbsPlantillaSB12(WebServiceFeature... features) {
		return super.getPort(new QName("http://claro.com.pe/eai/ws/ventas/plantillaws", "ebsPlantillaSB12"),
				PlantillaWSPortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (PLANTILLAWSSERVICE_EXCEPTION != null) {
			throw PLANTILLAWSSERVICE_EXCEPTION;
		}
		return PLANTILLAWSSERVICE_WSDL_LOCATION;
	}

}
